### ISSUE TITLE
Can't `npm install` on npm 2.14.15

### ISSUE THREAD

**Issue by vankasteelj** [gyzerok/nodecast-js#4]
Hello,

Something seems broken with NPM. The only way I could get this module was to clone it, install dependencies, and build with grunt. Shouldn't this either be automated, or the npm package be 'ready' to use? 

Thx

**Comment by gyzerok** [comment]
Hi, @vankasteelj 

Can you describe what particular problem you have while installing from npm?

**Comment by vankasteelj** [comment]
I see you've republished, and now I can't reproduce^^

**Comment by gyzerok** [comment]
Yes, there were some changes since latest release. And after your issue I decided to publish new version.

Hope this package would be helpful :)
